FROM {base_image}

ARG rid
ARG optional_restore_args
RUN dotnet restore -r $rid -s https://dotnet.myget.org/F/dotnet-core/api/v3/index.json -s https://api.nuget.org/v3/index.json $optional_restore_args
