FROM {base_image}

ARG netcoreapp_version

WORKDIR test
RUN dotnet new console --framework netcoreapp$netcoreapp_version
RUN dotnet restore -s https://dotnet.myget.org/F/dotnet-core/api/v3/index.json -s https://api.nuget.org/v3/index.json
RUN dotnet build
